name: Build and Save Docker Compose Images

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Build images via Compose
        run: |
          docker compose build

      - name: Save images to tar
        run: |
          docker compose config | grep '^service:' | awk '{print $2}' | \
            while read svc; do
              docker save "${svc}:latest" > "${svc}-${{ github.sha }}.tar"
            done

      - name: Upload Docker image artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images-${{ github.sha }}
          path: |
            *.tar
          retention-days: 1
